### ISSUE TITLE
How can I fix this error

### ISSUE THREAD

**Issue by adnanmahmoud96** [udacity/ud839_Miwok#106]
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'API'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

**Comment by Kvaibhav01** [comment]
Hi there! This isn't an error. Instead, it's a warning. Your app will definitely compile and run. 

Android Studio is recommending this so that your project can adopt the [new dependency configurations](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph) introduced in Gradle plugin 3.4.

You can see the complete list of new and deprecated configurations in the table given [here](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration?utm_source=android-studio#new_configurations).

**Comment by SudKul** [comment]
This will not occur now. 
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
