### ISSUE TITLE
failed to find Build Tools revision 27.0.3 Install Build Tools 27.0.3 and sync project

### ISSUE THREAD

**Issue by saoodahmad** [udacity/ud839_Miwok#133]
failed to find Build Tools revision 27.0.3
Install Build Tools 27.0.3 and sync project
installed sdk platform are:-
9.0, 8.0, 7.1.1, 6.0

**Comment by Kvaibhav01** [comment]
You just need to click on the _Install Build Tools 27.0.3 and sync project_ link and Android Studio will automatically install and sync the project.

See the companion solution [here](https://www.youtube.com/watch?v=l7AwiqYLkWY).

**Comment by devjaiye** [comment]
If you encounter this issue. simply go this website to download the required build tool for your project  https://androidsdkmanager.azurewebsites.net/Buildtools

Step 2 >> Extract the downloaded file

Step 3 >> Locate the build-tools folder inside your SDK e.g 
 **(C:\Android\Sdk\build-tools)**

Step 4 >> Paste the folder in the **build-tools** In my case, The default folder name was **"Android-10"** after I extracted the file but I change it to **29.0.2** since that's the issue I wanted to solve 

Step 5 >> Rebuild your project :) .. Done!
 

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/Rcaki.png

**Comment by RoustamManookian** [comment]
Thank you, you made my day and night!!!!

**Comment by zhaofeipeter** [comment]
Thanks

**Comment by devjaiye** [comment]
You're welcome

**Comment by emondd4** [comment]
and i couldn't find 27.0.3 version :(

**Comment by emondd4** [comment]
**This Solved my Problem!**

> Here is the actual 27.0.3 sdk build tool download link!


https://stackoverflow.com/a/51628434/13304913
