### ISSUE TITLE
why it take so long for  building the project ?

### ISSUE THREAD

**Issue by navotera** [udacity/ud839_Miwok#20]
i download this then import this project in android studio but it just loading saying that "Building miwok gradle project info". 

my environment is : 
windows 10. android studio 2.3

**Comment by LexLunatic** [comment]
Hey Navotera,
i am a udacity student like you, but wants to help anyways :D 
So what does "so long" mean? did you paused the course there? or did you just skipped it? what was your solution? Can i still help you?

Oh and for the future tell us your specification of hardware as well, since it is your computer which does the work:)

**Comment by navotera** [comment]
thanks u for your suggestion and respond. 
sorry for my late reply, yes it works it just need some time for my machine to arrange the project.

**Comment by Awais2017** [comment]
hello there how are you , i  have the same issue its taking to much time should i wait for it ?

**Comment by Kvaibhav01** [comment]
Hey @Awais2017! Let your device do its thing. It might take some time to work depending upon your machine hardware. Make sure you have a proper and steady internet connection with good speed.

**Comment by Awais2017** [comment]
Thank  u so much for your response.I understand now .thanks alot
