### ISSUE TITLE
Tutorial Codes Pre-written!

### ISSUE THREAD

**Issue by SandeepGamot** [udacity/ud839_Miwok#46]
On importing this file, i found out that most of the upcoming tutorial's code is already inside mainActivity.java/also the 4 activities were already included.

**Comment by Kvaibhav01** [comment]
@SandeepGamot, which file are you talking about? The [last commit](https://github.com/udacity/ud839_Miwok/commit/a9564ae1f0cbc3358bb62a8b8c83b3f6b59b61ca) on this repo was made on Feb 10, 2016 and since then I couldn't see any extra changes done. Tutorial code is provided so that we can code easily! :)

**Comment by SandeepGamot** [comment]
yeah exactly,I didn't want so much done already.So removed the whole project and made it from scratch.Loved the experience.

**Comment by Kvaibhav01** [comment]
You can now close this issue. 😀
